# Magral Theme Config
title: Magral Blog
author: 
  name: Kevin。
  url: /

dateFormat: YYYY, MMM DD

logo:
  img:  # image url
  name: Magral


version: 0.1.0

# dev settings

dev: true
devPort: 60002

# ---------- #


sass:
  compressed: true
  save: true
  prefix: prod_
  autoprefixer: false
  sourceMap: true

  theme: light

  light:
    background: '#FFF'
    primaryColor: '#2F66FF'
    gradualColor: '#494FF0'
    secondaryColor: '#E7EDFF'

    contrast: '#EA7079'
    contrastSecondary: '#FFEEEF'

    footer: $primaryColor

    primaryFontColor: '#414141'
    secondaryFontColor: '#707070'
    tertiaryFontColor: '#A9A9A9'

    border: '#CFCFCF'

  dark:
    background: "#000"
    primaryColor: '#2F66FF'
    gradualColor: '#494FF0'
    secondaryColor: '#E7EDFF'

    contrast: '#EA7079'
    contrastSecondary: '#FFEEEF'
  
icons:
  - icon: iconfont icon-github
    name: Github
    url: https://github.com/Kevin0z0
  - icon: iconfont icon-instagram
    name: Instagram
    size: 2.3
    url: https://www.instagram.com/tinycococo/
  - icon: iconfont icon-weixin
    img: /medias/qrcode.jpg
    width: 10
    title: 微信

highlight:
  enable: true

banner:
  switchTime: 5000

menu:
  index:
    name: Home
    url: /
  ctf:
    name: CTF
    url: /categories/ctf
    children:
      - name: WEB
        url: /tags/web
        icon: fab fa-edge
      - name: MISC
        url: /tags/misc
        icon: fas fa-tools
      - name: PWN
        url: /tags/pwn
        icon: fas fa-bomb
      - name: CRYPTO
        url: /tags/crypto
        icon: fas fa-unlock
      - name: REVERSE
        url: /tags/reverse
        icon: fas fa-terminal
  programming:
    name: Programming
    url: /categories/编程
    children:
      - name: HTML
        url: /tags/html
        icon: fab fa-html5
      - name: Python
        url: /tags/python
        icon: fab fa-python
      - name: C++
        url: /tags/c++
        icon: fas fa-stream
      - name: 算法
        url: /tags/算法
        icon: fas fa-brain
  study:
    name: Study
    url: /categories/study
    children:
      - name: 操作系统
        url: /tags/os
        icon: fab fa-windows
  contact:
    name: Contact
    url: /contact
  friends:
    name: Friends
    url: /friends
  about:
    name: About
    url: /about

footer:
  poweredBy: 
    name: Hexo
    url: https://hexo.io/zh-cn/

  theme:
    name: Magral
    url: https://github.com/Kevin0z0/hexo-theme-Magral

copyright: 
  start: 2020
  name: Kevin。
  url: /

record: #备案信息
  enable: true
  name: 浙ICP备18024727号
  url: http://beian.miit.gov.cn/

subtitle:
  enable: true
  loop: true # 是否循环
  showCursor: true # 是否显示光标
  startDelay: 300 # 开始延迟
  typeSpeed: 100 # 打字速度
  backSpeed: 60 # 删除速度
  sentences:
    - 从来没有真正的绝境, 只有心灵的迷途
    - Never really desperate, only the lost of the soul

recommend:
  enable: false
  name: Recommend

article:
  name: Articles

svgBackground:
  enable: true
  color: "#ffdfe1"

markdown:
  tag_rotate: true